[package]
name = "sdk-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
tree-sitter = "0.25.3"
tree-sitter-cpp = "0.23.4"
walkdir = "2.5.0"
clap = { version = "4.5.31", features = ["derive"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"